version: "3.9"

services:
    web:
        build:
            dockerfile: Catalog.Api\Dockerfile
        restart: always
        ports:
            - "8000:80"
        depends_on:
            - db-server

    db-server:
        image: postgres:latest
        environment:
            - POSTRES_USER=postgres
            - POSTGRES_PASSWORD=1234
        ports:
            - "5432:5432"